import os
from fastapi import FastAPI, WebSocket, WebSocketDisconnect, Depends, HTTPException, Query, status
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import FileResponse
from pathlib import Path

from config import settings
from database import engine, Base
from routers import auth, videos, violations
from services.ws_manager import ws_manager
from services.s3_service import storage_service

# Automatically create database tables if they do not exist
Base.metadata.create_all(bind=engine)

app = FastAPI(
    title="Traffic Violation Detection Platform API",
    description="SaaS Backend for Traffic Violation Detection using YOLOv8 + EasyOCR",
    version="1.0.0"
)

# CORS Middleware config
# Allow local React dev server and wildcard for WebSocket testing
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Register API Routers under /api
app.include_router(auth.router, prefix="/api")
app.include_router(videos.router, prefix="/api")
app.include_router(violations.router, prefix="/api")

# --- SECURE MEDIA SERVING ENDPOINT (S3 Presigned URL Emulator) ---
@app.get("/media/{file_path:path}")
def serve_signed_media(
    file_path: str,
    expires: int = Query(..., description="Expiration timestamp (seconds since epoch)"),
    signature: str = Query(..., description="HMAC-SHA256 signature verifying link authenticity")
):
    """
    Serves local files securely. Verifies that the URL was generated by our server,
    corresponds to the requested file, and has not expired.
    """
    # Verify signature
    if not storage_service.verify_local_url(file_path, expires, signature):
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="Signed URL is invalid or has expired"
        )
        
    # Resolve file path on disk
    local_file = settings.MEDIA_DIR / file_path
    
    # Secure path traversal check
    try:
        resolved_file = local_file.resolve()
        resolved_media_dir = settings.MEDIA_DIR.resolve()
        if not str(resolved_file).startswith(str(resolved_media_dir)):
            raise HTTPException(status_code=status.HTTP_403_FORBIDDEN, detail="Access denied")
    except Exception:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="File path error")

    if not local_file.exists() or not local_file.is_file():
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="File not found")
        
    return FileResponse(str(local_file))


# --- WEBSOCKET ENDPOINT ---
@app.websocket("/ws/video/{video_id}")
async def websocket_video_status(websocket: WebSocket, video_id: str):
    await ws_manager.connect(websocket, video_id)
    try:
        # Keep connection open. Send ping or listen for disconnect
        while True:
            data = await websocket.receive_text()
            # Echo or process if needed, currently we only broadcast updates downstream
            await websocket.send_text(f"Received heartbeat: {data}")
    except WebSocketDisconnect:
        ws_manager.disconnect(websocket, video_id)
    except Exception as e:
        print(f"WS Exception on video {video_id}: {e}")
        ws_manager.disconnect(websocket, video_id)


# Root/Health check
@app.get("/")
def read_root():
    return {
        "status": "healthy",
        "service": "Traffic Violation Platform Backend",
        "local_storage_path": str(settings.MEDIA_DIR)
    }
